UPDATE shows SET title = 'Adventure Time' WHERE title LIKE 'adven%';
UPDATE shows SET title = 'Arrow' WHERE title LIKE '%row';
UPDATE shows SET title = 'Avatar: The Last Airbender' WHERE title LIKE 'avatar%';
UPDATE shows SET title = 'Brooklyn Nine-Nine' WHERE title LIKE 'b%9';
UPDATE shows SET title = 'Community' WHERE title LIKE '%unity';
UPDATE shows SET title = 'Family Guy' WHERE title LIKE '%guy';
UPDATE shows SET title = 'Friends' WHERE title LIKE '%ends';
UPDATE shows SET title = 'Game of Thrones' WHERE title LIKE 'g%' AND title like '%t';
UPDATE shows SET title = 'Gilmore Girls' WHERE title LIKE 'gil%';
UPDATE shows SET title = "Grey's Anatomy" WHERE title LIKE '%anatomy';
UPDATE shows SET title = "How I Met Your Mother" WHERE title LIKE '%mother';
UPDATE shows SET title = "It's Always Sunny in Philadelphia" WHERE title LIKE '%delphia';
UPDATE shows SET title = "Parks and Recreation" WHERE title LIKE 'parks%';
UPDATE shows SET title = "Sherlock" WHERE title LIKE 'sher%';
UPDATE shows SET title = "Squid Game" WHERE title LIKE 'squid%'
UPDATE shows SET title = "The Bachelorette" WHERE title LIKE '%rette'
UPDATE shows SET title = "The Crown" WHERE title LIKE '%crown'
UPDATE shows SET title = "The Queen's Gambit" WHERE title LIKE '%gambit'
UPDATE shows SET title = "The Untamed" WHERE title like '%untamed';